require_relative 'wechat_api/basics'
require_relative 'wechat_api/manage_user'
require_relative 'wechat_api/manage_user_group'
require_relative 'wechat_api/material'
require_relative 'wechat_api/menu'
require_relative 'wechat_api/send_peer_msg'
require_relative 'wechat_api/send_group_msg'
